Models/CandidateModel.cs
using System.ComponentModel.DataAnnotations;
namespace Crud.Models
{
    public class CandidateModel
    {

        public int CandidateId { get; set; }
        public string? Name { get; set; }
        public int GenderId { get; set; }
        public string? Gender { get; set; }
        public string? SkillSet { get; set; }
        public List<string>? Skills { get; set; }
        public string? Phone { get; set; }
        public string? Email { get; set; }
        public string? Address { get; set; }
        public int CountryId { get; set; }
        public string? CountryName { get; set; }
        public int CreatedBy { get; set; }
    }
}

Models/CountryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Crud.Models
{
    public class CountryModel
    {
        public int Id { get; set; }
        public string? CountryName { get; set; }
        public int CreatedBy { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace Crud.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Crud.Helper;
using Crud.Models;
using Crud.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace Crud.Controllers
{
    [Route("[controller]")]
    public class CandidateController : Controller
    {
        private readonly ILogger<CandidateController> _logger;
        private readonly ICandidateService _candidateService;


        public CandidateController(ILogger<CandidateController> logger, ICandidateService candidateService)
        {
            _logger = logger;
            _candidateService = candidateService;
        }

        [HttpGet("/Index")]
        public async Task<IActionResult> Index()
        {
            var candidates = new List<CandidateModel>();
            var res = await _candidateService.GetAllAsync();

            if (res.IsSuccess && res.Value != null)
            {
                candidates = res.Value;
            }

            return View("Index", candidates);
        }

        [HttpGet("/Registration")]
        public IActionResult Registration()
        {
            return View();
        }
        private async Task<List<SelectListItem>> GetCountryList()
        {

            // var countries = new List<SelectListItem>();


            var countries = Shared.SessionData._CountryList;

            if (countries != null && countries.Count > 0)
            {
                return countries.Select(x => new SelectListItem() { Value = x.Id.ToString(), Text = x.CountryName }).ToList();
            }

            var result = await _candidateService.GetCountries();

            if (result.IsSuccess && result.Value != null)
            {
                Shared.SessionData._CountryList = result.Value;
                return Shared.SessionData._CountryList.Select(x => new SelectListItem() { Value = x.Id.ToString(), Text = x.CountryName }).ToList();
            }


            return new List<SelectListItem>();


            //     var countries = new List<SelectListItem>
            // {
            //     new SelectListItem()
            //     {
            //         Value = "1",
            //         Text = "India"
            //     },
            //      new SelectListItem()
            //     {
            //         Value = "2",
            //         Text = "Russia"
            //     },
            //      new SelectListItem()
            //     {
            //         Value = "3",
            //         Text = "America"
            //     }
            // };
            // return countries;
        }
        private List<string> GetSkillList()
        {
            var skills = new List<string>
        {
            "C","C++","Java","C#","React"
        };
            return skills;
        }

        [HttpGet("/GetRegistrationForm")]
        public async Task<IActionResult> GetRegisterForm(int index)
        {
            ViewData["skillList"] = GetSkillList();

            var countries = await GetCountryList();
            ViewData["countryList"] = countries;

            ViewData["FormIndex"] = index;

            return PartialView("_RegisterFormPartial", new CandidateModel());
        }

        [HttpPost("SaveCandidates")]
        public async Task<IActionResult> SaveCandidatesAsync([FromBody] List<CandidateModel> candidates)
        {
            if (candidates == null || !candidates.Any())
            {
                return Json(new { success = false, message = "No candidates received." });
            }

            var userId = 1;
            var res = await _candidateService.InsertBulkAsync(candidates, userId);

            if (res.IsFailed)
            {
                ViewBag.Message = $"An error occurred ! , {res.Errors.FirstOrDefault()?.Message}";
                return Json(new { success = false, message = "An error occurred." });
            }

            return Json(new { success = true, message = "Candidates saved successfully." });
        }


        [HttpPost("/SaveCandidate")]
        public async Task<IActionResult> Save([FromBody] CandidateModel entity)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", entity);
            }

            entity.CreatedBy = 1;

            var res = await _candidateService.InsertAsync(entity);

            if (res.IsFailed)
            {
                ViewBag.ErrorMessage = $"An error occurred ! , {res.Errors.FirstOrDefault()?.Message}";
                return Json(new { success = false, message = "An error occurred." });
            }

            return Json(new { success = true, message = "Candidates Updated successfully." });
        }

        [HttpGet("/Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {

            if (id < 1)
            {
                ViewBag.ErrorMessage = "Invlaid Candidate Id.";
                return RedirectToAction(nameof(Index));
            }

            var deletedBy = 1;
            var res = await _candidateService.DeleteAsync(id, deletedBy);

            if (res.IsFailed)
            {
                ViewBag.Message(ErrorHelper.ConvertErrors(res.Errors));
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("/Candidate_Registration/{id}")]
        public async Task<IActionResult> CandidateRegistrationAsync(int id)
        {
            var entity = new CandidateModel();

            ViewData["skillList"] = GetSkillList();
            var countries = await GetCountryList();
            ViewData["countryList"] = countries;

            if (id > 0)
            {
                var res = await _candidateService.GetAsync(id);

                if (res.IsFailed)
                {
                    var error = res.Errors.FirstOrDefault()?.Message ?? "candidate not found !";
                    ViewBag.ErrorMessage = error;
                    return RedirectToAction(nameof(Index));
                }

                entity = res.Value;
            }
            else
            {
                entity.Skills = new List<string>();
            }

            return View("Create", entity);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Crud.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Crud.Services;
using System.Threading.Tasks;

namespace Crud.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly ICandidateService _candidateService;

    public HomeController(ILogger<HomeController> logger, ICandidateService candidateService)
    {
        _logger = logger;
        _candidateService = candidateService;
    }

    public IActionResult Index()
    {
        // var candidates = new List<CandidateModel>();
        // var res = await _candidateService.GetAllAsync();

        // if (res.IsSuccess && res.Value != null)
        // {
        //     candidates = res.Value;
        // }

        return View();
    }


    public IActionResult Privacy()
    {

        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Candidate/Create.cshtml
@model Crud.Models.CandidateModel
@{
    Layout = "_Layout";
}

<link rel="stylesheet" href="~/lib/bootstrap-icons/bootstrap-icons.min.css" />


<div class="container-fluid col-lg-12 p-3 shadow-lg" id="box-container">
    <div class="d-flex align-items-center pt-3">
        <a type="button" class="btn btn-sm btn-floating" id="btn-back" onclick="window.history.back()">
            <i class="bi bi-arrow-left-circle fs-3"></i>
        </a>

        <span id="title" class="ms-4 mt-0 fs-5">Candidate</span>
    </div>

    <input type="hidden" id="ID" name="ID" value=@Model.CandidateId />

    <div id="register-container" class="register-container ps-4 ">
        @await Html.PartialAsync("_RegisterFormPartial", this.Model)
    </div>

    <button type="" id="btn-cancel" class="btn btn-danger" onclick="window.history.back()">Cancel</button>
    <button type="" id="btn-save" class="btn btn-success">Save</button>
</div>

@if (ViewBag.Message != null)

{
    <div class="alert alert-danger mt-3">
        @ViewBag.Message
    </div>

}

@section Scripts
{
    <script src="~/js/candidateReg.js" asp-append-version="true"></script>
}

Views/Candidate/Index.cshtml
@model List<CandidateModel>
@{
    ViewData["Title"] = "Candidate List";
}
<div class="container-fluid col-lg-12 p-3 shadow-lg">

    <div class="d-flex align-items-center pt-3">
        @* <a type="button" class="btn btn-sm btn-floating" id="btn-back" onclick="window.history.back()">
            <i class="bi bi-arrow-left-circle fs-3"></i>
        </a> *@

        <span id="title" class="ms-4 mt-0 fs-5"> @ViewData["Title"]</span>
    </div>

    <a asp-controller="Candidate" asp-action="Registration" class="btn btn-primary mb-3">Add Candidate</a>

    <table id="candidate-table" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Candidate Name</th>
                <th>Gender</th>
                <th>Skills</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Address</th>
                <th>Country</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var candidate in Model)
            {
                <tr>
                    <td>@candidate.CountryName</td>
                    <td>@candidate.Gender</td>
                    <td>@candidate.Skills</td>
                    <td>@candidate.Phone</td>
                    <td>@candidate.Email</td>
                    <td>@candidate.Address</td>
                    <td>@candidate.CountryName</td>

                    <td>
                        <a href="javascript:void(0);" id="edit-btn" data-id="@candidate.CandidateId"
                            class="btn btn-warning btn-sm edit-btn">Edit</a>
                        <a href="javascript:void(0);" id="delete-btn" data-id="@candidate.CandidateId"
                            class="btn btn-danger btn-sm delete-btn">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@if (ViewBag.ErrorMessage != null)

{
    <div class="alert alert-danger mt-3">
        @ViewBag.ErrorMessage
    </div>

}

@if (ViewBag.Message != null)
{
    <div class="alert alert-success mt-3">
        @ViewBag.Message
    </div>
}

@section Scripts {
    <script>
        $(document).ready(function () {

            $('#userTable').DataTable({
                paging: true,
                searching: true,
                ordering: true,
                pageLength: 10,
                lengthMenu: [5, 10, 25, 50, 100],
                language: {
                    search: "Filter records:",
                    lengthMenu: "Show _MENU_ entries",
                },
                columnDefs: [
                    { orderable: false, targets: 3 }
                ]
            });


            $('.edit-btn').on('click', function () {
                console.log("Test Edit");

                var candidateId = $(this).data('id');

                Swal.fire({
                    title: 'Are you sure you want to edit this Candidate?',
                    text: 'You can modify the candidate details.',
                    icon: 'question',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, Edit it!',
                    cancelButtonText: 'No, Cancel'
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location.href = '/Edit/' + candidateId; // Redirect to the Edit page
                    }
                });
            });

            // Delete button click event
            $('.delete-btn').on('click', function () {
                var candidateId = $(this).data('id');

                Swal.fire({
                    title: 'Are you sure you want to delete this Candidate?',
                    text: 'This action is irreversible!',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Yes, Delete it!',
                    cancelButtonText: 'No, Cancel'
                }).then((result) => {
                    if (result.isConfirmed) {

                        window.location.href = '/Delete/' + candidateId;
                    }
                });
            });
        }); 
    </script>

}

Views/Candidate/Registration.cshtml
@model CandidateModel;
@{
    ViewData["Title"] = "Home Page";
}


<div class="container-fluid col-lg-12 p-3 shadow-lg" id="box-container">
    <div class="d-flex align-items-center pt-3">
        <a type="button" class="btn btn-sm btn-floating" id="btn-back" onclick="window.history.back()">
            <i class="bi bi-arrow-left-circle fs-3"></i>
        </a>

        <span id="title" class="ms-4 mt-0 fs-5 mb-5"> Candidate Registration</span>
    </div>



    <div id="register-container" class="register-container ps-4 ">

    </div>

    <div id="error-tag" class="alert alert-danger" hidden></div>

    <button type="" id="btn-add" class="btn btn-primary">Add</button>
    <button type="" id="btn-save" class="btn btn-success">Submit</button>
    <input type="hidden" id="form-index" name="FormIndex" value="0" data-index="0" />

</div>

@section Scripts
{
    <script src="~/js/candidate.js" asp-append-version="true"></script>
}

Views/Candidate/_RegisterFormPartial.cshtml
@model CandidateModel;
@{
    @* var skillSetList = ViewBag.skillList as List<string>;
    var countryList = ViewBag.countryList as List<SelectListItem>;
    var selectedSkills = Model.Skills ?? new List<string>();
    var index = ViewData["FormIndex"] ?? 0; *@

    var skillSetList = ViewData["skillList"] as List<string>;
    var countryList = ViewData["countryList"] as List<SelectListItem>;
    var selectedSkills = Model.Skills ?? new List<string>();
    var index = ViewData["FormIndex"] ?? 0;
}

<div class="register-form mb-5" style="width: 400px;" data-index="@index">
    @Html.HiddenFor(m => m.CandidateId)

    <div class="input-control mb-3">
        <label>Name <span class="text-danger">*</span></label>
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", id = "candidate-name" })
        <div class="error text-danger"></div>
    </div>

    <div class="input-control mb-3">
        <label>Gender <span class="text-danger">*</span></label><br />
        <input type="radio" name="Gender_@index" value="1" @(Model.GenderId == 1 ? "checked" : "") /> Male
        <input type="radio" name="Gender_@index" value="2" @(Model.GenderId == 2 ? "checked" : "") /> Female
        <input type="radio" name="Gender_@index" value="3" @(Model.GenderId == 3 ? "checked" : "") /> Other
        <div class="error text-danger"></div>
    </div>

    <div class="input-control mb-3">
        <label>Skills <span class="text-danger">*</span></label><br />
        @foreach (var skill in skillSetList)
        {
            <input type="checkbox" name="skills" value="@skill" class="chk-skills" @(selectedSkills.Contains(skill) ?
                                                                                               "checked" : "") /> @skill

                }
        <div class="error text-danger"></div>
    </div>

    <div class="input-control mb-3">
        <label>Phone <span class="text-danger">*</span></label>
        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", id = "phone" })
        <div class="error text-danger"></div>
    </div>

    <div class="input-control mb-3">
        <label>Email <span class="text-danger">*</span></label>
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", id = "email" })
        <div class="error text-danger"></div>
    </div>

    <div class="input-control mb-3">
        <label>Address</label>
        @Html.TextAreaFor(m => m.Address, new { @class = "form-control" })
        <div class="error text-danger"></div>
    </div>

    <div class="input-control mb-3">
        <label>Country <span class="text-danger">*</span></label>
        @Html.DropDownListFor(m => m.CountryId, countryList, "-- Select Country --", new
        { @class = "form-control", id = "country" })
        <div class="error text-danger"></div>
    </div>

</div>
<hr class="mb-8">

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Crud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Crud.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/DataTables/datatables.min.css" />
    <link rel="stylesheet" href="~/lib/sweetalert2/dist/sweetalert2.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/bootstrap-icons.min.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Crud</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Candidate"
                                asp-action="Index">Candidate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Crud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/DataTables/datatables.min.js"></script>
    <script src="~/lib/sweetalert2/dist/sweetalert2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>